// Generated by CoffeeScript 1.6.3
(function() {
  var Subject, SubjectScheme, app, db, express, mongoose;

  express = require("express");

  mongoose = require("mongoose");

  app = express();

  app.use(express.bodyParser());

  mongoose.connect('mongodb://localhost/zoomash');

  db = mongoose.connection;

  SubjectScheme = new mongoose.Schema({
    id: 'string',
    location: 'string',
    rank: 'number',
    random: 'number'
  });

  Subject = mongoose.model('Subject', SubjectScheme);

  app.get('/subjects', function(req, res) {
    return Subject.find({
      random: {
        "$gt": Math.random()
      }
    }).sort("random").limit(1).execFind(function(err, subject) {
      return res.json(subject);
    });
  });

  app.get('/topshots', function(req, res) {
    return Subject.find().sort({"rank":-1}).limit(9).execFind(function(err, subject) {
      return res.json(subject);
    });
  });

  app.post("/classification", function(req, res) {
    var classification;
    classification = req.body;
    Subject.update({
      _id: classification.id
    }, {
      rank: classification.rank
    }, function(err, subject) {
      return console.log("SUBJECT", subject);
    });
    return res.json(true);
  });

  app.use(express["static"](__dirname));

  app.listen(process.env.PORT || 8000);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
